version: build{build}
image: Visual Studio 2017
clone_folder: C:\CK-World\CK-Core-Projects\CK-Text
branches:
  only:
    - master
    - develop
    - test-azure-feed
environment:
  VSS_NUGET_EXTERNAL_FEED_ENDPOINTS:
    secure: secure: Nz3VB+UKkzYqapOqgvXXKyXzU4AaS1bYdFCyljXRvRXet2HcR8uhb2PtNaSFV9DyPOeG6XQpknjqtb0dx0KZ9riDPODiybYmta0aMXhz7EpUVHuDevZ1P4V2WK6xOZTWtCA5weTL6spdP80vsVARsT8AVl2/1NTfJghHpG33vzQ0nIBgLsKck4Lov0btb4zDTA5ePXasipIZzsxIS+41WRuOYebRo8Jt2J4f8TKimBJi+2I6443CopVv6JcnB2og3AcgB7EeiTpJcDGDRf4U7rjagzCkQkyDhivN/Ia5y0NJAolQ5FabqO24mr+rAQ5KZH7myeXyicgXNuxIjnVr2V/NaCjXLwthn1a5MDTYGCryilNA/mFkPrS/FsJnx6oS+ZMnlRL1W5rTZm2nQ59Tzr71Vld3ITv5wcz9Q8pejvhc888ujYl1oLd5zsLSqQHxKZpDAs2Y9WdQVenkDqwgvIn0zqSFoI6y/WFOtAnHlmWgaOU1C/L9kTpe76lwDWX6QhkpCIbCKIfDDXThxNpyiJtCnjEH9Oo1ilhnJkz/bpGSmBTH6IYQfKO4Lx0xIRP+mZQnWZ4CQy7RGvLQJP0vD0zy+/CViNhU87w5gUX+wRhmNfq+sHAdm3jX7Cx6yYjJmGLX7bcUmZUQOif9NOUHNLdzWCL5K4YvFLYmn2P23YnfImSpQIbKM3FrKJRWC3RP6NDKggNo4DwIHgn0SKe99mYy9NYU6iWld/UrfjbaiC15P/4hl4zRP4WJrVLQi3px9dmdfwcmCWlziUKdqS/V120Avo8xKGHA0ro9BCVN6OYZUV3lSWFDWHUY3rhgsso7SbPNsvMiugSVcjL2o9qY0SCMqetQgGX8GmL/+fsWZMF24u+D6QAE5rgxuQcER/iL2VTi3eJDSBxbEJVmOrf1dkgSkrN/vn9SoANYvm69djxJ1NQ5J+Xr7/lnIJUCTjQw1y6KBROrAo/J1PAVB+ta9NQsjZYKNOmI+qp+waVg7dHMal9jGQg3u8l9ns9ObdLykyP6oQUTGtqVWLizZa3uVq6oYcm8mvzf5NnURrhW48/NTvfLkoGmXlEuW3lHa6jLBo6rixG5pQW2vMjeyM5HXrSUSecwHVVf5uuRaoPOtUj3RcJbvt5sIve0Jh65hiH47kq8Px6Nr6YPUcWmR5wTTXSOSpcvGPDiE8KaayDKTeo=
# 
#    {"endpointCredentials": [
#      {"endpoint":"https://pkgs.dev.azure.com/Signature-OpenSource/_packaging/Stable/nuget/v3/index.json",
#       "username":"SignatureOpenSourceAzurePackaging",
#       "password":"xxx"},
#      {"endpoint":"https://pkgs.dev.azure.com/Signature-OpenSource/_packaging/Latest/nuget/v3/index.json",
#       "username":"SignatureOpenSourceAzurePackaging",
#       "password":"xxx"},
#      {"endpoint":"https://pkgs.dev.azure.com/Signature-OpenSource/_packaging/Preview/nuget/v3/index.json",
#       "username":"SignatureOpenSourceAzurePackaging",
#       "password":"xxx"},
#      {"endpoint":"https://pkgs.dev.azure.com/Signature-OpenSource/_packaging/CI/nuget/v3/index.json",
#       "username":"SignatureOpenSourceAzurePackaging",
#       "password":"xxx"}
#       ]}

#install:
#  - CodeCakeBuilder/Installcredprovider.ps1 -AddNetfx 
build_script:
  - dotnet run --project CodeCakeBuilder -nointeraction
test: off
