version: build{build}
image: Visual Studio 2017
clone_folder: C:\CK-World\CK-Core-Projects\CK-Text
branches:
  only:
    - master
    - develop
    - test-azure-feed
environment:
  AZURE_FEED_SIGNATURE_OPENSOURCE_PAT:
     secure: MOjOpNMfab3UseEjZW3bGL6+7uXkbmExMOLMn2Mg+61uUO0qdrSZ28DsChFgR60/Huc+D2bcJ/GXP4CB8Cb8Vg==

install:
    # This installs the Azure Credential Provider. 
  - ps: ./CodeCakeBuilder/InstallCredentialProvider.ps1 -AddNetfx 
build_script:
  - dotnet run --project CodeCakeBuilder -nointeraction
test: off
