version: build{build}
image: Visual Studio 2017
clone_folder: C:\CK-World\CK-Core-Projects\CK-Text
branches:
  only:
    - master
    - develop
    - test-azure-feed
environment:

  # Workaround for dev/NuGet.Client\src\NuGet.Core\NuGet.Protocol\Plugins\PluginFactory.cs line 161:
  #   FileName = Environment.GetEnvironmentVariable("DOTNET_HOST_PATH"),
  # This line should be:
  #   FileName = Environment.GetEnvironmentVariable("DOTNET_HOST_PATH") ?? "dotnet",
  DOTNET_HOST_PATH: dotnet

  VSS_PAT:
     secure: x5MPTKJr8Dkb0Yol0fgmWWx7VtM6Q51VxMFY896zhgTMkX3xv9091ZDxJKf/EtqS/Lry0bW45FswBknEEQ+XYg==

  VSS_NUGET_EXTERNAL_FEED_ENDPOINTS:
    secure: Nz3VB+UKkzYqapOqgvXXK0wAQkcbjlc7sjrwhYTA7zZ5MdEedplC/poHzeJh2jLFi/qniofrG9Pe8qz8l/CV2mK/1F8vPXuo7csnGxeuR27I9qKPDZncV7VtCuKHDL7DRDiQKyua1ZP5ZlVLsVmNhuQ/wc7s3zvE3Kk4a7pN/qR80fs1ZTGBKxqMrNVIACkkZq8dICYk4cko/SO9DUKyw+hvA99ehzlYcq/C9PISrBkrC9MB0tVQQXto6zqrmPKKL67cg/D52tT95iV4mxqhupWy9OzfiFfHnN9SRMldnpsa+wU7ajr7l2tBCOK4XxGu+F/JfFwbZADqbyWdZeGPjA==
# 
#    {"endpointCredentials": [
#      {"endpoint":"https://pkgs.dev.azure.com/Signature-OpenSource/_packaging/Default/nuget/v3/index.json",
#       "username":"SignatureOpenSourceAzurePackaging",
#       "password":"VSS_PAT"}
#       ]}

install:
  - ps: ./CodeCakeBuilder/InstallCredentialProvider.ps1 -AddNetfx 
build_script:
  - dotnet run --project CodeCakeBuilder -nointeraction
test: off
